
package com.lzf.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://ws.lzf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.lzf.ws.client.Users
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.lzf.com/", className = "com.lzf.ws.client.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.lzf.com/", className = "com.lzf.ws.client.GetUserResponse")
    public Users getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sya", targetNamespace = "http://ws.lzf.com/", className = "com.lzf.ws.client.Sya")
    @ResponseWrapper(localName = "syaResponse", targetNamespace = "http://ws.lzf.com/", className = "com.lzf.ws.client.SyaResponse")
    public String sya(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
