
package com.lzf.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceImpService", targetNamespace = "http://ws.lzf.com/", wsdlLocation = "http://localhost/services/Service?wsdl")
public class ServiceImpService
    extends Service
{

    private final static URL SERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEIMPSERVICE_EXCEPTION;
    private final static QName SERVICEIMPSERVICE_QNAME = new QName("http://ws.lzf.com/", "ServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/services/Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEIMPSERVICE_WSDL_LOCATION = url;
        SERVICEIMPSERVICE_EXCEPTION = e;
    }

    public ServiceImpService() {
        super(__getWsdlLocation(), SERVICEIMPSERVICE_QNAME);
    }

    public ServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEIMPSERVICE_QNAME, features);
    }

    public ServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEIMPSERVICE_QNAME);
    }

    public ServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEIMPSERVICE_QNAME, features);
    }

    public ServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "ServiceImpPort")
    public IService getServiceImpPort() {
        return super.getPort(new QName("http://ws.lzf.com/", "ServiceImpPort"), IService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "ServiceImpPort")
    public IService getServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lzf.com/", "ServiceImpPort"), IService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEIMPSERVICE_EXCEPTION!= null) {
            throw SERVICEIMPSERVICE_EXCEPTION;
        }
        return SERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
